language: python

env:
 - WAGTAIL_VERSION=1.13.1
 - WAGTAIL_VERSION=1.12.2

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"

matrix:
  exclude:
  - python: "2.7"
    env: WAGTAIL_VERSION=2.0
  - python: "pypy"
    env: WAGTAIL_VERSION=2.0

install:
 - pip install -r requirements/tests.txt
 - pip install -q wagtail==$WAGTAIL_VERSION

script:
 - python runtests.py
